# Generated by Django 3.2.8 on 2021-10-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='servicio',
            field=models.CharField(default=1, max_length=40, verbose_name='servicio'),
            preserve_default=False,
        ),
    ]
